# Generated by Django 3.1.2 on 2020-12-18 21:26
# This file was automatically generated by Django during the migration process.
# It modifies the "code" field in the "Room" model to use a custom function for generating unique codes.

import api.models
# Importing the models module from the "api" app to access custom functionality like generate_unique_code.

from django.db import migrations, models
# Importing Django's migrations module to define database operations and models module for field types.

class Migration(migrations.Migration):
    # A subclass of `migrations.Migration` that defines the changes for this migration.

    dependencies = [
        # Specifies the migration file that this migration depends on.
        ('api', '0001_initial'),
        # This migration depends on the initial migration of the "api" app (0001_initial).
    ]

    operations = [
        # List of operations to apply in this migration.
        migrations.AlterField(
            # Modifies an existing field in the "Room" model.
            model_name='room',  # The name of the model where the field exists.
            name='code',  # The name of the field being modified.

            # Updates the "code" field to use a custom function for generating unique codes.
            field=models.CharField(
                default=api.models.generate_unique_code,  # Custom function to generate a default value for the field.
                max_length=8,  # Limits the field's string length to 8 characters.
                unique=True,  # Ensures all values in this field are unique across the table.
            ),
        ),
    ]
