# Generated by Django 3.1.2 on 2020-12-21 23:38
# This file was automatically generated by Django during the migration process.
# It adds a new field `current_song` to the "Room" model.

from django.db import migrations, models
# Importing Django's migrations and models modules.
# The `migrations` module is used to define database operations, and the `models` module provides field types.

class Migration(migrations.Migration):
    # A subclass of `migrations.Migration` that defines the changes for this migration.

    dependencies = [
        # Specifies the migration file that this migration depends on.
        ('api', '0002_auto_20201218_1626'),
        # This migration depends on the migration "0002_auto_20201218_1626" in the `api` app.
    ]

    operations = [
        # List of operations to apply in this migration.
        migrations.AddField(
            # Adds a new field to an existing model.
            model_name='room',  # The name of the model where the field is being added.
            name='current_song',  # The name of the new field being added.

            # Defines the characteristics of the new field.
            field=models.CharField(
                max_length=50,  # Limits the field's string length to 50 characters.
                null=True,  # Allows this field to have a `NULL` value in the database (optional field).
            ),
        ),
    ]
